jwt:
  header: Authorization
  secretKey-accessToken : ThisIsSecretKeyAccessLFEKMMVDAPGMVCXEPGIYQSKZE #AccessToken SecretKey
  secretKey-refreshToken : ThisIsSecretKeyRefreshEIJSLBJiJRIJGTIESKMCNEIY #RefreshToken SecretKey
  accessToken-valid-seconds : 1800 #30분
  refreshToken-valid-seconds : 86400 #24시간
origin:
  signal-url: https://ttaallkk.herokuapp.com
  front-url: https://ttaallkk.vercel.app
admin:
  email: admin@admin.com

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/security?characterEncoding=utf-8; #db경로
    username: root
    password: 2
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 28795000 #(mariadb wait time out(28800sec)) - (5sec)
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #JPA 방언(표준ANSI SQL문법 이외의 문법사용을 위한 기능). 
        show_sql: true #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력.
        format_sql: true #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현.
        #use_sql_comments: true #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력.
        search:
          lucene_version: LATEST
          default:
            diretory_provider: filessystem
            #indexBase: D:/hibernateSearchIndex #하이버네이트 서치 인덱스 데이터 저장될 위치. 지정하지 않으면 내장 기본값으로 적용
#server:
  #port: 8081 #port 설정
  #ssl:  #https 설정
    #enable: true
    #key-store: /etc/letsencrypt/live/mydomain.com/cert_and_key.p12 #letencrypt ssl인증서 생성된 경로
    #key-store-password: password #인증서 비밀번호
    #key-store-type: PKCS12 #인증서 타입(스프링의경우 PKCS12타입의 인증서로 변환해야 적용가능)