jwt:
  header: Authorization
  secretKey : ThisIsSecretKeyLFEKMMVDAPGMVCXEPGIYQSKZE #SecretKey
  accessToken-valid-seconds : 100 #1h
  refreshToken-valid-seconds : 86400 #24h

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/security?characterEncoding=utf-8; #db경로
    username: root
    password: 2
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #JPA 방언(표준ANSI SQL문법 이외의 문법사용을 위한 기능). 
        show_sql: true #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력.
        format_sql: true #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현.
        use_sql_comments: true #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력.
